package org.dykman.jn.android.view;
public class KeyEvent extends android.view.KeyEvent{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public KeyEvent(int arg1,int arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public KeyEvent(long arg1,long arg2,int arg3,int arg4,int arg5, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4, arg5); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5 } ); }
public KeyEvent(long arg1,long arg2,int arg3,int arg4,int arg5,int arg6, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4, arg5, arg6); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5, arg6 } ); }
public KeyEvent(long arg1,long arg2,int arg3,int arg4,int arg5,int arg6,int arg7,int arg8, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 } ); }
public KeyEvent(long arg1,long arg2,int arg3,int arg4,int arg5,int arg6,int arg7,int arg8,int arg9, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 } ); }
public KeyEvent(long arg1,java.lang.String arg2,int arg3,int arg4, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
public KeyEvent(android.view.KeyEvent arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public KeyEvent(android.view.KeyEvent arg1,long arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public java.lang.String toString(){ if (!testjnOverride( "toString" )) return super.toString(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "toString_" + jlocale + "_", null ); }
@Override public char getNumber(){ if (!testjnOverride( "getNumber" )) return super.getNumber(); return (java.lang.Character) jInterface.Jnido( this, jchildidx + "getNumber_" + jlocale + "_", null ); }
@Override public char getDisplayLabel(){ if (!testjnOverride( "getDisplayLabel" )) return super.getDisplayLabel(); return (java.lang.Character) jInterface.Jnido( this, jchildidx + "getDisplayLabel_" + jlocale + "_", null ); }
@Override public int getUnicodeChar(){ if (!testjnOverride( "getUnicodeChar" )) return super.getUnicodeChar(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getUnicodeChar_" + jlocale + "_", null ); }
@Override public int getUnicodeChar(int arg1) { if (!testjnOverride( "getUnicodeChar" )) return super.getUnicodeChar( arg1); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getUnicodeChar_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean getKeyData(android.view.KeyCharacterMap.KeyData arg1) { if (!testjnOverride( "getKeyData" )) return super.getKeyData( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getKeyData_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public char getMatch(char[] arg1) { if (!testjnOverride( "getMatch" )) return super.getMatch( arg1); return (java.lang.Character) jInterface.Jnido( this, jchildidx + "getMatch_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public char getMatch(char[] arg1,int arg2) { if (!testjnOverride( "getMatch" )) return super.getMatch( arg1, arg2); return (java.lang.Character) jInterface.Jnido( this, jchildidx + "getMatch_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean isPrintingKey(){ if (!testjnOverride( "isPrintingKey" )) return super.isPrintingKey(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isPrintingKey_" + jlocale + "_", null ); }
@Override public int describeContents(){ if (!testjnOverride( "describeContents" )) return super.describeContents(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "describeContents_" + jlocale + "_", null ); }
@Override public void writeToParcel(android.os.Parcel arg1,int arg2) { if (!testjnOverride( "writeToParcel" )) { super.writeToParcel( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "writeToParcel_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
}
