package org.dykman.jn.android.content;
public class Intent extends android.content.Intent{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public Intent(String jlocale,String jchildid,String joverride ){ super(); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", null ); }
public Intent(android.content.Intent arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public Intent(java.lang.String arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public Intent(java.lang.String arg1,android.net.Uri arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public Intent(android.content.Context arg1,java.lang.Class arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public Intent(java.lang.String arg1,android.net.Uri arg2,android.content.Context arg3,java.lang.Class arg4, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
@Override public java.lang.String toString(){ if (!testjnOverride( "toString" )) return super.toString(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "toString_" + jlocale + "_", null ); }
@Override public java.lang.String getPackage(){ if (!testjnOverride( "getPackage" )) return super.getPackage(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getPackage_" + jlocale + "_", null ); }
@Override public java.lang.String getType(){ if (!testjnOverride( "getType" )) return super.getType(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getType_" + jlocale + "_", null ); }
@Override public java.lang.String getScheme(){ if (!testjnOverride( "getScheme" )) return super.getScheme(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getScheme_" + jlocale + "_", null ); }
@Override public java.lang.String toURI(){ if (!testjnOverride( "toURI" )) return super.toURI(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "toURI_" + jlocale + "_", null ); }
@Override public android.net.Uri getData(){ if (!testjnOverride( "getData" )) return super.getData(); return (android.net.Uri) jInterface.Jnido( this, jchildidx + "getData_" + jlocale + "_", null ); }
@Override public android.content.Intent cloneFilter(){ if (!testjnOverride( "cloneFilter" )) return super.cloneFilter(); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "cloneFilter_" + jlocale + "_", null ); }
@Override public java.lang.String getAction(){ if (!testjnOverride( "getAction" )) return super.getAction(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getAction_" + jlocale + "_", null ); }
@Override public java.lang.String getDataString(){ if (!testjnOverride( "getDataString" )) return super.getDataString(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getDataString_" + jlocale + "_", null ); }
@Override public java.lang.String resolveType(android.content.Context arg1) { if (!testjnOverride( "resolveType" )) return super.resolveType( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "resolveType_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String resolveType(android.content.ContentResolver arg1) { if (!testjnOverride( "resolveType" )) return super.resolveType( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "resolveType_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String resolveTypeIfNeeded(android.content.ContentResolver arg1) { if (!testjnOverride( "resolveTypeIfNeeded" )) return super.resolveTypeIfNeeded( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "resolveTypeIfNeeded_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean hasCategory(java.lang.String arg1) { if (!testjnOverride( "hasCategory" )) return super.hasCategory( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "hasCategory_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.util.Set getCategories(){ if (!testjnOverride( "getCategories" )) return super.getCategories(); return (java.util.Set) jInterface.Jnido( this, jchildidx + "getCategories_" + jlocale + "_", null ); }
@Override public void setExtrasClassLoader(java.lang.ClassLoader arg1) { if (!testjnOverride( "setExtrasClassLoader" )) { super.setExtrasClassLoader( arg1); return; } jInterface.Jnido( this, jchildidx + "setExtrasClassLoader_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean hasExtra(java.lang.String arg1) { if (!testjnOverride( "hasExtra" )) return super.hasExtra( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "hasExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean hasFileDescriptors(){ if (!testjnOverride( "hasFileDescriptors" )) return super.hasFileDescriptors(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "hasFileDescriptors_" + jlocale + "_", null ); }
@Override public boolean getBooleanExtra(java.lang.String arg1,boolean arg2) { if (!testjnOverride( "getBooleanExtra" )) return super.getBooleanExtra( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getBooleanExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public byte getByteExtra(java.lang.String arg1,byte arg2) { if (!testjnOverride( "getByteExtra" )) return super.getByteExtra( arg1, arg2); return (java.lang.Byte) jInterface.Jnido( this, jchildidx + "getByteExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public short getShortExtra(java.lang.String arg1,short arg2) { if (!testjnOverride( "getShortExtra" )) return super.getShortExtra( arg1, arg2); return (java.lang.Short) jInterface.Jnido( this, jchildidx + "getShortExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public char getCharExtra(java.lang.String arg1,char arg2) { if (!testjnOverride( "getCharExtra" )) return super.getCharExtra( arg1, arg2); return (java.lang.Character) jInterface.Jnido( this, jchildidx + "getCharExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public int getIntExtra(java.lang.String arg1,int arg2) { if (!testjnOverride( "getIntExtra" )) return super.getIntExtra( arg1, arg2); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIntExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public long getLongExtra(java.lang.String arg1,long arg2) { if (!testjnOverride( "getLongExtra" )) return super.getLongExtra( arg1, arg2); return (java.lang.Long) jInterface.Jnido( this, jchildidx + "getLongExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public float getFloatExtra(java.lang.String arg1,float arg2) { if (!testjnOverride( "getFloatExtra" )) return super.getFloatExtra( arg1, arg2); return (java.lang.Float) jInterface.Jnido( this, jchildidx + "getFloatExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public double getDoubleExtra(java.lang.String arg1,double arg2) { if (!testjnOverride( "getDoubleExtra" )) return super.getDoubleExtra( arg1, arg2); return (java.lang.Double) jInterface.Jnido( this, jchildidx + "getDoubleExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public java.lang.String getStringExtra(java.lang.String arg1) { if (!testjnOverride( "getStringExtra" )) return super.getStringExtra( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getStringExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.CharSequence getCharSequenceExtra(java.lang.String arg1) { if (!testjnOverride( "getCharSequenceExtra" )) return super.getCharSequenceExtra( arg1); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "getCharSequenceExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.os.Parcelable getParcelableExtra(java.lang.String arg1) { if (!testjnOverride( "getParcelableExtra" )) return super.getParcelableExtra( arg1); return (android.os.Parcelable) jInterface.Jnido( this, jchildidx + "getParcelableExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.os.Parcelable[] getParcelableArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getParcelableArrayExtra" )) return super.getParcelableArrayExtra( arg1); return (android.os.Parcelable[]) jInterface.Jnidox( this, jchildidx + "getParcelableArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.util.ArrayList getParcelableArrayListExtra(java.lang.String arg1) { if (!testjnOverride( "getParcelableArrayListExtra" )) return super.getParcelableArrayListExtra( arg1); return (java.util.ArrayList) jInterface.Jnido( this, jchildidx + "getParcelableArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.io.Serializable getSerializableExtra(java.lang.String arg1) { if (!testjnOverride( "getSerializableExtra" )) return super.getSerializableExtra( arg1); return (java.io.Serializable) jInterface.Jnido( this, jchildidx + "getSerializableExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.util.ArrayList getIntegerArrayListExtra(java.lang.String arg1) { if (!testjnOverride( "getIntegerArrayListExtra" )) return super.getIntegerArrayListExtra( arg1); return (java.util.ArrayList) jInterface.Jnido( this, jchildidx + "getIntegerArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.util.ArrayList getStringArrayListExtra(java.lang.String arg1) { if (!testjnOverride( "getStringArrayListExtra" )) return super.getStringArrayListExtra( arg1); return (java.util.ArrayList) jInterface.Jnido( this, jchildidx + "getStringArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean[] getBooleanArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getBooleanArrayExtra" )) return super.getBooleanArrayExtra( arg1); return (boolean[]) jInterface.Jnidoz( this, jchildidx + "getBooleanArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public byte[] getByteArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getByteArrayExtra" )) return super.getByteArrayExtra( arg1); return (byte[]) jInterface.Jnidoc( this, jchildidx + "getByteArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public short[] getShortArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getShortArrayExtra" )) return super.getShortArrayExtra( arg1); return (short[]) jInterface.Jnidos( this, jchildidx + "getShortArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public char[] getCharArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getCharArrayExtra" )) return super.getCharArrayExtra( arg1); return (char[]) jInterface.Jnidow( this, jchildidx + "getCharArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int[] getIntArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getIntArrayExtra" )) return super.getIntArrayExtra( arg1); return (int[]) jInterface.Jnidoi( this, jchildidx + "getIntArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public long[] getLongArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getLongArrayExtra" )) return super.getLongArrayExtra( arg1); return (long[]) jInterface.Jnidol( this, jchildidx + "getLongArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public float[] getFloatArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getFloatArrayExtra" )) return super.getFloatArrayExtra( arg1); return (float[]) jInterface.Jnidof( this, jchildidx + "getFloatArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public double[] getDoubleArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getDoubleArrayExtra" )) return super.getDoubleArrayExtra( arg1); return (double[]) jInterface.Jnidod( this, jchildidx + "getDoubleArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String[] getStringArrayExtra(java.lang.String arg1) { if (!testjnOverride( "getStringArrayExtra" )) return super.getStringArrayExtra( arg1); return (java.lang.String[]) jInterface.Jnidox( this, jchildidx + "getStringArrayExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.os.Bundle getBundleExtra(java.lang.String arg1) { if (!testjnOverride( "getBundleExtra" )) return super.getBundleExtra( arg1); return (android.os.Bundle) jInterface.Jnido( this, jchildidx + "getBundleExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.os.Bundle getExtras(){ if (!testjnOverride( "getExtras" )) return super.getExtras(); return (android.os.Bundle) jInterface.Jnido( this, jchildidx + "getExtras_" + jlocale + "_", null ); }
@Override public int getFlags(){ if (!testjnOverride( "getFlags" )) return super.getFlags(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getFlags_" + jlocale + "_", null ); }
@Override public android.content.ComponentName getComponent(){ if (!testjnOverride( "getComponent" )) return super.getComponent(); return (android.content.ComponentName) jInterface.Jnido( this, jchildidx + "getComponent_" + jlocale + "_", null ); }
@Override public android.graphics.Rect getSourceBounds(){ if (!testjnOverride( "getSourceBounds" )) return super.getSourceBounds(); return (android.graphics.Rect) jInterface.Jnido( this, jchildidx + "getSourceBounds_" + jlocale + "_", null ); }
@Override public android.content.ComponentName resolveActivity(android.content.pm.PackageManager arg1) { if (!testjnOverride( "resolveActivity" )) return super.resolveActivity( arg1); return (android.content.ComponentName) jInterface.Jnido( this, jchildidx + "resolveActivity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.pm.ActivityInfo resolveActivityInfo(android.content.pm.PackageManager arg1,int arg2) { if (!testjnOverride( "resolveActivityInfo" )) return super.resolveActivityInfo( arg1, arg2); return (android.content.pm.ActivityInfo) jInterface.Jnido( this, jchildidx + "resolveActivityInfo_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent setAction(java.lang.String arg1) { if (!testjnOverride( "setAction" )) return super.setAction( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setAction_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setData(android.net.Uri arg1) { if (!testjnOverride( "setData" )) return super.setData( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setData_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setType(java.lang.String arg1) { if (!testjnOverride( "setType" )) return super.setType( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setType_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setDataAndType(android.net.Uri arg1,java.lang.String arg2) { if (!testjnOverride( "setDataAndType" )) return super.setDataAndType( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setDataAndType_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent addCategory(java.lang.String arg1) { if (!testjnOverride( "addCategory" )) return super.addCategory( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "addCategory_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void removeCategory(java.lang.String arg1) { if (!testjnOverride( "removeCategory" )) { super.removeCategory( arg1); return; } jInterface.Jnido( this, jchildidx + "removeCategory_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,boolean arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,byte arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,char arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,short arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,int arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,long arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,float arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,double arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,java.lang.String arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,java.lang.CharSequence arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,android.os.Parcelable arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,android.os.Parcelable[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,java.io.Serializable arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,boolean[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,byte[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,short[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,char[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,int[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,long[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,float[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,double[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,java.lang.String[] arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtra(java.lang.String arg1,android.os.Bundle arg2) { if (!testjnOverride( "putExtra" )) return super.putExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putParcelableArrayListExtra(java.lang.String arg1,java.util.ArrayList arg2) { if (!testjnOverride( "putParcelableArrayListExtra" )) return super.putParcelableArrayListExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putParcelableArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putIntegerArrayListExtra(java.lang.String arg1,java.util.ArrayList arg2) { if (!testjnOverride( "putIntegerArrayListExtra" )) return super.putIntegerArrayListExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putIntegerArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putStringArrayListExtra(java.lang.String arg1,java.util.ArrayList arg2) { if (!testjnOverride( "putStringArrayListExtra" )) return super.putStringArrayListExtra( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putStringArrayListExtra_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent putExtras(android.content.Intent arg1) { if (!testjnOverride( "putExtras" )) return super.putExtras( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtras_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent putExtras(android.os.Bundle arg1) { if (!testjnOverride( "putExtras" )) return super.putExtras( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "putExtras_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent replaceExtras(android.content.Intent arg1) { if (!testjnOverride( "replaceExtras" )) return super.replaceExtras( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "replaceExtras_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent replaceExtras(android.os.Bundle arg1) { if (!testjnOverride( "replaceExtras" )) return super.replaceExtras( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "replaceExtras_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void removeExtra(java.lang.String arg1) { if (!testjnOverride( "removeExtra" )) { super.removeExtra( arg1); return; } jInterface.Jnido( this, jchildidx + "removeExtra_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setFlags(int arg1) { if (!testjnOverride( "setFlags" )) return super.setFlags( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setFlags_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent addFlags(int arg1) { if (!testjnOverride( "addFlags" )) return super.addFlags( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "addFlags_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setPackage(java.lang.String arg1) { if (!testjnOverride( "setPackage" )) return super.setPackage( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setPackage_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setComponent(android.content.ComponentName arg1) { if (!testjnOverride( "setComponent" )) return super.setComponent( arg1); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setComponent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.content.Intent setClassName(android.content.Context arg1,java.lang.String arg2) { if (!testjnOverride( "setClassName" )) return super.setClassName( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setClassName_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent setClassName(java.lang.String arg1,java.lang.String arg2) { if (!testjnOverride( "setClassName" )) return super.setClassName( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setClassName_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.content.Intent setClass(android.content.Context arg1,java.lang.Class arg2) { if (!testjnOverride( "setClass" )) return super.setClass( arg1, arg2); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "setClass_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setSourceBounds(android.graphics.Rect arg1) { if (!testjnOverride( "setSourceBounds" )) { super.setSourceBounds( arg1); return; } jInterface.Jnido( this, jchildidx + "setSourceBounds_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int fillIn(android.content.Intent arg1,int arg2) { if (!testjnOverride( "fillIn" )) return super.fillIn( arg1, arg2); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "fillIn_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean filterEquals(android.content.Intent arg1) { if (!testjnOverride( "filterEquals" )) return super.filterEquals( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "filterEquals_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int filterHashCode(){ if (!testjnOverride( "filterHashCode" )) return super.filterHashCode(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "filterHashCode_" + jlocale + "_", null ); }
@Override public java.lang.String toUri(int arg1) { if (!testjnOverride( "toUri" )) return super.toUri( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "toUri_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int describeContents(){ if (!testjnOverride( "describeContents" )) return super.describeContents(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "describeContents_" + jlocale + "_", null ); }
@Override public void writeToParcel(android.os.Parcel arg1,int arg2) { if (!testjnOverride( "writeToParcel" )) { super.writeToParcel( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "writeToParcel_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void readFromParcel(android.os.Parcel arg1) { if (!testjnOverride( "readFromParcel" )) { super.readFromParcel( arg1); return; } jInterface.Jnido( this, jchildidx + "readFromParcel_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
