package org.dykman.jn.android.graphics.drawable;
public class NinePatchDrawable extends android.graphics.drawable.NinePatchDrawable{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public NinePatchDrawable(android.graphics.Bitmap arg1,byte[] arg2,android.graphics.Rect arg3,java.lang.String arg4, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
public NinePatchDrawable(android.content.res.Resources arg1,android.graphics.Bitmap arg2,byte[] arg3,android.graphics.Rect arg4,java.lang.String arg5, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4, arg5); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5 } ); }
public NinePatchDrawable(android.graphics.NinePatch arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public NinePatchDrawable(android.content.res.Resources arg1,android.graphics.NinePatch arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void inflate(android.content.res.Resources arg1,org.xmlpull.v1.XmlPullParser arg2,android.util.AttributeSet arg3) throws org.xmlpull.v1.XmlPullParserException,java.io.IOException { if (!testjnOverride( "inflate" )) { super.inflate( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "inflate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void setTargetDensity(android.graphics.Canvas arg1) { if (!testjnOverride( "setTargetDensity" )) { super.setTargetDensity( arg1); return; } jInterface.Jnido( this, jchildidx + "setTargetDensity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setTargetDensity(android.util.DisplayMetrics arg1) { if (!testjnOverride( "setTargetDensity" )) { super.setTargetDensity( arg1); return; } jInterface.Jnido( this, jchildidx + "setTargetDensity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setTargetDensity(int arg1) { if (!testjnOverride( "setTargetDensity" )) { super.setTargetDensity( arg1); return; } jInterface.Jnido( this, jchildidx + "setTargetDensity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void draw(android.graphics.Canvas arg1) { if (!testjnOverride( "draw" )) { super.draw( arg1); return; } jInterface.Jnido( this, jchildidx + "draw_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getChangingConfigurations(){ if (!testjnOverride( "getChangingConfigurations" )) return super.getChangingConfigurations(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getChangingConfigurations_" + jlocale + "_", null ); }
@Override public boolean getPadding(android.graphics.Rect arg1) { if (!testjnOverride( "getPadding" )) return super.getPadding( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getPadding_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setAlpha(int arg1) { if (!testjnOverride( "setAlpha" )) { super.setAlpha( arg1); return; } jInterface.Jnido( this, jchildidx + "setAlpha_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setColorFilter(android.graphics.ColorFilter arg1) { if (!testjnOverride( "setColorFilter" )) { super.setColorFilter( arg1); return; } jInterface.Jnido( this, jchildidx + "setColorFilter_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setDither(boolean arg1) { if (!testjnOverride( "setDither" )) { super.setDither( arg1); return; } jInterface.Jnido( this, jchildidx + "setDither_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setFilterBitmap(boolean arg1) { if (!testjnOverride( "setFilterBitmap" )) { super.setFilterBitmap( arg1); return; } jInterface.Jnido( this, jchildidx + "setFilterBitmap_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.graphics.Paint getPaint(){ if (!testjnOverride( "getPaint" )) return super.getPaint(); return (android.graphics.Paint) jInterface.Jnido( this, jchildidx + "getPaint_" + jlocale + "_", null ); }
@Override public int getIntrinsicWidth(){ if (!testjnOverride( "getIntrinsicWidth" )) return super.getIntrinsicWidth(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIntrinsicWidth_" + jlocale + "_", null ); }
@Override public int getIntrinsicHeight(){ if (!testjnOverride( "getIntrinsicHeight" )) return super.getIntrinsicHeight(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIntrinsicHeight_" + jlocale + "_", null ); }
@Override public int getMinimumWidth(){ if (!testjnOverride( "getMinimumWidth" )) return super.getMinimumWidth(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getMinimumWidth_" + jlocale + "_", null ); }
@Override public int getMinimumHeight(){ if (!testjnOverride( "getMinimumHeight" )) return super.getMinimumHeight(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getMinimumHeight_" + jlocale + "_", null ); }
@Override public int getOpacity(){ if (!testjnOverride( "getOpacity" )) return super.getOpacity(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getOpacity_" + jlocale + "_", null ); }
@Override public android.graphics.Region getTransparentRegion(){ if (!testjnOverride( "getTransparentRegion" )) return super.getTransparentRegion(); return (android.graphics.Region) jInterface.Jnido( this, jchildidx + "getTransparentRegion_" + jlocale + "_", null ); }
@Override public android.graphics.drawable.Drawable mutate(){ if (!testjnOverride( "mutate" )) return super.mutate(); return (android.graphics.drawable.Drawable) jInterface.Jnido( this, jchildidx + "mutate_" + jlocale + "_", null ); }
}
