package org.dykman.jn.android.graphics.drawable;
public class ShapeDrawable extends android.graphics.drawable.ShapeDrawable{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public ShapeDrawable(String jlocale,String jchildid,String joverride ){ super(); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", null ); }
public ShapeDrawable(android.graphics.drawable.shapes.Shape arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void inflate(android.content.res.Resources arg1,org.xmlpull.v1.XmlPullParser arg2,android.util.AttributeSet arg3) throws org.xmlpull.v1.XmlPullParserException,java.io.IOException { if (!testjnOverride( "inflate" )) { super.inflate( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "inflate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public android.graphics.drawable.shapes.Shape getShape(){ if (!testjnOverride( "getShape" )) return super.getShape(); return (android.graphics.drawable.shapes.Shape) jInterface.Jnido( this, jchildidx + "getShape_" + jlocale + "_", null ); }
@Override public void setShape(android.graphics.drawable.shapes.Shape arg1) { if (!testjnOverride( "setShape" )) { super.setShape( arg1); return; } jInterface.Jnido( this, jchildidx + "setShape_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setShaderFactory(android.graphics.drawable.ShapeDrawable.ShaderFactory arg1) { if (!testjnOverride( "setShaderFactory" )) { super.setShaderFactory( arg1); return; } jInterface.Jnido( this, jchildidx + "setShaderFactory_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.graphics.Paint getPaint(){ if (!testjnOverride( "getPaint" )) return super.getPaint(); return (android.graphics.Paint) jInterface.Jnido( this, jchildidx + "getPaint_" + jlocale + "_", null ); }
@Override public void setPadding(int arg1,int arg2,int arg3,int arg4) { if (!testjnOverride( "setPadding" )) { super.setPadding( arg1, arg2, arg3, arg4); return; } jInterface.Jnido( this, jchildidx + "setPadding_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
@Override public void setPadding(android.graphics.Rect arg1) { if (!testjnOverride( "setPadding" )) { super.setPadding( arg1); return; } jInterface.Jnido( this, jchildidx + "setPadding_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setIntrinsicWidth(int arg1) { if (!testjnOverride( "setIntrinsicWidth" )) { super.setIntrinsicWidth( arg1); return; } jInterface.Jnido( this, jchildidx + "setIntrinsicWidth_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setIntrinsicHeight(int arg1) { if (!testjnOverride( "setIntrinsicHeight" )) { super.setIntrinsicHeight( arg1); return; } jInterface.Jnido( this, jchildidx + "setIntrinsicHeight_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getIntrinsicWidth(){ if (!testjnOverride( "getIntrinsicWidth" )) return super.getIntrinsicWidth(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIntrinsicWidth_" + jlocale + "_", null ); }
@Override public int getIntrinsicHeight(){ if (!testjnOverride( "getIntrinsicHeight" )) return super.getIntrinsicHeight(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIntrinsicHeight_" + jlocale + "_", null ); }
@Override public boolean getPadding(android.graphics.Rect arg1) { if (!testjnOverride( "getPadding" )) return super.getPadding( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getPadding_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onDraw(android.graphics.drawable.shapes.Shape arg1,android.graphics.Canvas arg2,android.graphics.Paint arg3) { if (!testjnOverride( "onDraw" )) { super.onDraw( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "onDraw_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void draw(android.graphics.Canvas arg1) { if (!testjnOverride( "draw" )) { super.draw( arg1); return; } jInterface.Jnido( this, jchildidx + "draw_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getChangingConfigurations(){ if (!testjnOverride( "getChangingConfigurations" )) return super.getChangingConfigurations(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getChangingConfigurations_" + jlocale + "_", null ); }
@Override public void setAlpha(int arg1) { if (!testjnOverride( "setAlpha" )) { super.setAlpha( arg1); return; } jInterface.Jnido( this, jchildidx + "setAlpha_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setColorFilter(android.graphics.ColorFilter arg1) { if (!testjnOverride( "setColorFilter" )) { super.setColorFilter( arg1); return; } jInterface.Jnido( this, jchildidx + "setColorFilter_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getOpacity(){ if (!testjnOverride( "getOpacity" )) return super.getOpacity(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getOpacity_" + jlocale + "_", null ); }
@Override public void setDither(boolean arg1) { if (!testjnOverride( "setDither" )) { super.setDither( arg1); return; } jInterface.Jnido( this, jchildidx + "setDither_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onBoundsChange(android.graphics.Rect arg1) { if (!testjnOverride( "onBoundsChange" )) { super.onBoundsChange( arg1); return; } jInterface.Jnido( this, jchildidx + "onBoundsChange_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected boolean inflateTag(java.lang.String arg1,android.content.res.Resources arg2,org.xmlpull.v1.XmlPullParser arg3,android.util.AttributeSet arg4) { if (!testjnOverride( "inflateTag" )) return super.inflateTag( arg1, arg2, arg3, arg4); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "inflateTag_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
@Override public android.graphics.drawable.Drawable mutate(){ if (!testjnOverride( "mutate" )) return super.mutate(); return (android.graphics.drawable.Drawable) jInterface.Jnido( this, jchildidx + "mutate_" + jlocale + "_", null ); }
}
