package org.dykman.jn.android.widget;
public class ExpandableListView extends android.widget.ExpandableListView{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public ExpandableListView(android.content.Context arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public ExpandableListView(android.content.Context arg1,android.util.AttributeSet arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public ExpandableListView(android.content.Context arg1,android.util.AttributeSet arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override protected void dispatchDraw(android.graphics.Canvas arg1) { if (!testjnOverride( "dispatchDraw" )) { super.dispatchDraw( arg1); return; } jInterface.Jnido( this, jchildidx + "dispatchDraw_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setChildDivider(android.graphics.drawable.Drawable arg1) { if (!testjnOverride( "setChildDivider" )) { super.setChildDivider( arg1); return; } jInterface.Jnido( this, jchildidx + "setChildDivider_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setOnItemClickListener(android.widget.AdapterView.OnItemClickListener arg1) { if (!testjnOverride( "setOnItemClickListener" )) { super.setOnItemClickListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnItemClickListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.widget.ExpandableListAdapter getExpandableListAdapter(){ if (!testjnOverride( "getExpandableListAdapter" )) return super.getExpandableListAdapter(); return (android.widget.ExpandableListAdapter) jInterface.Jnido( this, jchildidx + "getExpandableListAdapter_" + jlocale + "_", null ); }
@Override public boolean performItemClick(android.view.View arg1,int arg2,long arg3) { if (!testjnOverride( "performItemClick" )) return super.performItemClick( arg1, arg2, arg3); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "performItemClick_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public boolean expandGroup(int arg1) { if (!testjnOverride( "expandGroup" )) return super.expandGroup( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "expandGroup_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean collapseGroup(int arg1) { if (!testjnOverride( "collapseGroup" )) return super.collapseGroup( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "collapseGroup_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setOnGroupCollapseListener(android.widget.ExpandableListView.OnGroupCollapseListener arg1) { if (!testjnOverride( "setOnGroupCollapseListener" )) { super.setOnGroupCollapseListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnGroupCollapseListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setOnGroupExpandListener(android.widget.ExpandableListView.OnGroupExpandListener arg1) { if (!testjnOverride( "setOnGroupExpandListener" )) { super.setOnGroupExpandListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnGroupExpandListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setOnGroupClickListener(android.widget.ExpandableListView.OnGroupClickListener arg1) { if (!testjnOverride( "setOnGroupClickListener" )) { super.setOnGroupClickListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnGroupClickListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setOnChildClickListener(android.widget.ExpandableListView.OnChildClickListener arg1) { if (!testjnOverride( "setOnChildClickListener" )) { super.setOnChildClickListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnChildClickListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public long getExpandableListPosition(int arg1) { if (!testjnOverride( "getExpandableListPosition" )) return super.getExpandableListPosition( arg1); return (java.lang.Long) jInterface.Jnido( this, jchildidx + "getExpandableListPosition_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getFlatListPosition(long arg1) { if (!testjnOverride( "getFlatListPosition" )) return super.getFlatListPosition( arg1); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getFlatListPosition_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public long getSelectedPosition(){ if (!testjnOverride( "getSelectedPosition" )) return super.getSelectedPosition(); return (java.lang.Long) jInterface.Jnido( this, jchildidx + "getSelectedPosition_" + jlocale + "_", null ); }
@Override public long getSelectedId(){ if (!testjnOverride( "getSelectedId" )) return super.getSelectedId(); return (java.lang.Long) jInterface.Jnido( this, jchildidx + "getSelectedId_" + jlocale + "_", null ); }
@Override public void setSelectedGroup(int arg1) { if (!testjnOverride( "setSelectedGroup" )) { super.setSelectedGroup( arg1); return; } jInterface.Jnido( this, jchildidx + "setSelectedGroup_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean setSelectedChild(int arg1,int arg2,boolean arg3) { if (!testjnOverride( "setSelectedChild" )) return super.setSelectedChild( arg1, arg2, arg3); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "setSelectedChild_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public boolean isGroupExpanded(int arg1) { if (!testjnOverride( "isGroupExpanded" )) return super.isGroupExpanded( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isGroupExpanded_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setChildIndicator(android.graphics.drawable.Drawable arg1) { if (!testjnOverride( "setChildIndicator" )) { super.setChildIndicator( arg1); return; } jInterface.Jnido( this, jchildidx + "setChildIndicator_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setChildIndicatorBounds(int arg1,int arg2) { if (!testjnOverride( "setChildIndicatorBounds" )) { super.setChildIndicatorBounds( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setChildIndicatorBounds_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setGroupIndicator(android.graphics.drawable.Drawable arg1) { if (!testjnOverride( "setGroupIndicator" )) { super.setGroupIndicator( arg1); return; } jInterface.Jnido( this, jchildidx + "setGroupIndicator_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setIndicatorBounds(int arg1,int arg2) { if (!testjnOverride( "setIndicatorBounds" )) { super.setIndicatorBounds( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setIndicatorBounds_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.os.Parcelable onSaveInstanceState(){ if (!testjnOverride( "onSaveInstanceState" )) return super.onSaveInstanceState(); return (android.os.Parcelable) jInterface.Jnido( this, jchildidx + "onSaveInstanceState_" + jlocale + "_", null ); }
@Override public void onRestoreInstanceState(android.os.Parcelable arg1) { if (!testjnOverride( "onRestoreInstanceState" )) { super.onRestoreInstanceState( arg1); return; } jInterface.Jnido( this, jchildidx + "onRestoreInstanceState_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
