package org.dykman.jn.android.widget;
public class TableLayout extends android.widget.TableLayout{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public TableLayout(android.content.Context arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
public TableLayout(android.content.Context arg1,android.util.AttributeSet arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setOnHierarchyChangeListener(android.view.ViewGroup.OnHierarchyChangeListener arg1) { if (!testjnOverride( "setOnHierarchyChangeListener" )) { super.setOnHierarchyChangeListener( arg1); return; } jInterface.Jnido( this, jchildidx + "setOnHierarchyChangeListener_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void requestLayout(){ if (!testjnOverride( "requestLayout" )) { super.requestLayout(); return; } jInterface.Jnido( this, jchildidx + "requestLayout_" + jlocale + "_", null ); }
@Override public boolean isShrinkAllColumns(){ if (!testjnOverride( "isShrinkAllColumns" )) return super.isShrinkAllColumns(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isShrinkAllColumns_" + jlocale + "_", null ); }
@Override public void setShrinkAllColumns(boolean arg1) { if (!testjnOverride( "setShrinkAllColumns" )) { super.setShrinkAllColumns( arg1); return; } jInterface.Jnido( this, jchildidx + "setShrinkAllColumns_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean isStretchAllColumns(){ if (!testjnOverride( "isStretchAllColumns" )) return super.isStretchAllColumns(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isStretchAllColumns_" + jlocale + "_", null ); }
@Override public void setStretchAllColumns(boolean arg1) { if (!testjnOverride( "setStretchAllColumns" )) { super.setStretchAllColumns( arg1); return; } jInterface.Jnido( this, jchildidx + "setStretchAllColumns_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setColumnCollapsed(int arg1,boolean arg2) { if (!testjnOverride( "setColumnCollapsed" )) { super.setColumnCollapsed( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setColumnCollapsed_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean isColumnCollapsed(int arg1) { if (!testjnOverride( "isColumnCollapsed" )) return super.isColumnCollapsed( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isColumnCollapsed_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setColumnStretchable(int arg1,boolean arg2) { if (!testjnOverride( "setColumnStretchable" )) { super.setColumnStretchable( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setColumnStretchable_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean isColumnStretchable(int arg1) { if (!testjnOverride( "isColumnStretchable" )) return super.isColumnStretchable( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isColumnStretchable_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setColumnShrinkable(int arg1,boolean arg2) { if (!testjnOverride( "setColumnShrinkable" )) { super.setColumnShrinkable( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setColumnShrinkable_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean isColumnShrinkable(int arg1) { if (!testjnOverride( "isColumnShrinkable" )) return super.isColumnShrinkable( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isColumnShrinkable_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void addView(android.view.View arg1) { if (!testjnOverride( "addView" )) { super.addView( arg1); return; } jInterface.Jnido( this, jchildidx + "addView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void addView(android.view.View arg1,int arg2) { if (!testjnOverride( "addView" )) { super.addView( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "addView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void addView(android.view.View arg1,android.view.ViewGroup.LayoutParams arg2) { if (!testjnOverride( "addView" )) { super.addView( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "addView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void addView(android.view.View arg1,int arg2,android.view.ViewGroup.LayoutParams arg3) { if (!testjnOverride( "addView" )) { super.addView( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "addView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override protected void onMeasure(int arg1,int arg2) { if (!testjnOverride( "onMeasure" )) { super.onMeasure( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onMeasure_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onLayout(boolean arg1,int arg2,int arg3,int arg4,int arg5) { if (!testjnOverride( "onLayout" )) { super.onLayout( arg1, arg2, arg3, arg4, arg5); return; } else super.onLayout( arg1, arg2, arg3, arg4, arg5); jInterface.Jnido( this, jchildidx + "onLayout_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5 } ); }
@Override protected boolean checkLayoutParams(android.view.ViewGroup.LayoutParams arg1) { if (!testjnOverride( "checkLayoutParams" )) return super.checkLayoutParams( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "checkLayoutParams_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
