package org.dykman.jn.android.database;
public class CursorWrapper extends android.database.CursorWrapper{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public CursorWrapper(android.database.Cursor arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public short getShort(int arg1) { if (!testjnOverride( "getShort" )) return super.getShort( arg1); return (java.lang.Short) jInterface.Jnido( this, jchildidx + "getShort_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getInt(int arg1) { if (!testjnOverride( "getInt" )) return super.getInt( arg1); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getInt_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public long getLong(int arg1) { if (!testjnOverride( "getLong" )) return super.getLong( arg1); return (java.lang.Long) jInterface.Jnido( this, jchildidx + "getLong_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public float getFloat(int arg1) { if (!testjnOverride( "getFloat" )) return super.getFloat( arg1); return (java.lang.Float) jInterface.Jnido( this, jchildidx + "getFloat_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public double getDouble(int arg1) { if (!testjnOverride( "getDouble" )) return super.getDouble( arg1); return (java.lang.Double) jInterface.Jnido( this, jchildidx + "getDouble_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void close(){ if (!testjnOverride( "close" )) { super.close(); return; } jInterface.Jnido( this, jchildidx + "close_" + jlocale + "_", null ); }
@Override public java.lang.String getString(int arg1) { if (!testjnOverride( "getString" )) return super.getString( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getString_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean isFirst(){ if (!testjnOverride( "isFirst" )) return super.isFirst(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isFirst_" + jlocale + "_", null ); }
@Override public boolean isClosed(){ if (!testjnOverride( "isClosed" )) return super.isClosed(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isClosed_" + jlocale + "_", null ); }
@Override public int getCount(){ if (!testjnOverride( "getCount" )) return super.getCount(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getCount_" + jlocale + "_", null ); }
@Override public void deactivate(){ if (!testjnOverride( "deactivate" )) { super.deactivate(); return; } jInterface.Jnido( this, jchildidx + "deactivate_" + jlocale + "_", null ); }
@Override public boolean moveToFirst(){ if (!testjnOverride( "moveToFirst" )) return super.moveToFirst(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveToFirst_" + jlocale + "_", null ); }
@Override public int getColumnCount(){ if (!testjnOverride( "getColumnCount" )) return super.getColumnCount(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getColumnCount_" + jlocale + "_", null ); }
@Override public int getColumnIndex(java.lang.String arg1) { if (!testjnOverride( "getColumnIndex" )) return super.getColumnIndex( arg1); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getColumnIndex_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getColumnIndexOrThrow(java.lang.String arg1) throws java.lang.IllegalArgumentException { if (!testjnOverride( "getColumnIndexOrThrow" )) return super.getColumnIndexOrThrow( arg1); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getColumnIndexOrThrow_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String getColumnName(int arg1) { if (!testjnOverride( "getColumnName" )) return super.getColumnName( arg1); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getColumnName_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String[] getColumnNames(){ if (!testjnOverride( "getColumnNames" )) return super.getColumnNames(); return (java.lang.String[]) jInterface.Jnidox( this, jchildidx + "getColumnNames_" + jlocale + "_", null ); }
@Override public android.os.Bundle getExtras(){ if (!testjnOverride( "getExtras" )) return super.getExtras(); return (android.os.Bundle) jInterface.Jnido( this, jchildidx + "getExtras_" + jlocale + "_", null ); }
@Override public void copyStringToBuffer(int arg1,android.database.CharArrayBuffer arg2) { if (!testjnOverride( "copyStringToBuffer" )) { super.copyStringToBuffer( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "copyStringToBuffer_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public byte[] getBlob(int arg1) { if (!testjnOverride( "getBlob" )) return super.getBlob( arg1); return (byte[]) jInterface.Jnidoc( this, jchildidx + "getBlob_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean getWantsAllOnMoveCalls(){ if (!testjnOverride( "getWantsAllOnMoveCalls" )) return super.getWantsAllOnMoveCalls(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getWantsAllOnMoveCalls_" + jlocale + "_", null ); }
@Override public boolean isAfterLast(){ if (!testjnOverride( "isAfterLast" )) return super.isAfterLast(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isAfterLast_" + jlocale + "_", null ); }
@Override public boolean isBeforeFirst(){ if (!testjnOverride( "isBeforeFirst" )) return super.isBeforeFirst(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isBeforeFirst_" + jlocale + "_", null ); }
@Override public boolean isLast(){ if (!testjnOverride( "isLast" )) return super.isLast(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isLast_" + jlocale + "_", null ); }
@Override public boolean isNull(int arg1) { if (!testjnOverride( "isNull" )) return super.isNull( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isNull_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean moveToLast(){ if (!testjnOverride( "moveToLast" )) return super.moveToLast(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveToLast_" + jlocale + "_", null ); }
@Override public boolean move(int arg1) { if (!testjnOverride( "move" )) return super.move( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "move_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean moveToPosition(int arg1) { if (!testjnOverride( "moveToPosition" )) return super.moveToPosition( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveToPosition_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean moveToNext(){ if (!testjnOverride( "moveToNext" )) return super.moveToNext(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveToNext_" + jlocale + "_", null ); }
@Override public int getPosition(){ if (!testjnOverride( "getPosition" )) return super.getPosition(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getPosition_" + jlocale + "_", null ); }
@Override public boolean moveToPrevious(){ if (!testjnOverride( "moveToPrevious" )) return super.moveToPrevious(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveToPrevious_" + jlocale + "_", null ); }
@Override public void registerContentObserver(android.database.ContentObserver arg1) { if (!testjnOverride( "registerContentObserver" )) { super.registerContentObserver( arg1); return; } jInterface.Jnido( this, jchildidx + "registerContentObserver_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void registerDataSetObserver(android.database.DataSetObserver arg1) { if (!testjnOverride( "registerDataSetObserver" )) { super.registerDataSetObserver( arg1); return; } jInterface.Jnido( this, jchildidx + "registerDataSetObserver_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean requery(){ if (!testjnOverride( "requery" )) return super.requery(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "requery_" + jlocale + "_", null ); }
@Override public android.os.Bundle respond(android.os.Bundle arg1) { if (!testjnOverride( "respond" )) return super.respond( arg1); return (android.os.Bundle) jInterface.Jnido( this, jchildidx + "respond_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setNotificationUri(android.content.ContentResolver arg1,android.net.Uri arg2) { if (!testjnOverride( "setNotificationUri" )) { super.setNotificationUri( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setNotificationUri_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void unregisterContentObserver(android.database.ContentObserver arg1) { if (!testjnOverride( "unregisterContentObserver" )) { super.unregisterContentObserver( arg1); return; } jInterface.Jnido( this, jchildidx + "unregisterContentObserver_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void unregisterDataSetObserver(android.database.DataSetObserver arg1) { if (!testjnOverride( "unregisterDataSetObserver" )) { super.unregisterDataSetObserver( arg1); return; } jInterface.Jnido( this, jchildidx + "unregisterDataSetObserver_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
