package org.dykman.jn.android.content.pm;
public class LabeledIntent extends android.content.pm.LabeledIntent{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public LabeledIntent(android.content.Intent arg1,java.lang.String arg2,int arg3,int arg4, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
public LabeledIntent(android.content.Intent arg1,java.lang.String arg2,java.lang.CharSequence arg3,int arg4, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3, arg4); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
public LabeledIntent(java.lang.String arg1,int arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
public LabeledIntent(java.lang.String arg1,java.lang.CharSequence arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public java.lang.String getSourcePackage(){ if (!testjnOverride( "getSourcePackage" )) return super.getSourcePackage(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getSourcePackage_" + jlocale + "_", null ); }
@Override public int getLabelResource(){ if (!testjnOverride( "getLabelResource" )) return super.getLabelResource(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getLabelResource_" + jlocale + "_", null ); }
@Override public java.lang.CharSequence getNonLocalizedLabel(){ if (!testjnOverride( "getNonLocalizedLabel" )) return super.getNonLocalizedLabel(); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "getNonLocalizedLabel_" + jlocale + "_", null ); }
@Override public int getIconResource(){ if (!testjnOverride( "getIconResource" )) return super.getIconResource(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getIconResource_" + jlocale + "_", null ); }
@Override public java.lang.CharSequence loadLabel(android.content.pm.PackageManager arg1) { if (!testjnOverride( "loadLabel" )) return super.loadLabel( arg1); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "loadLabel_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.graphics.drawable.Drawable loadIcon(android.content.pm.PackageManager arg1) { if (!testjnOverride( "loadIcon" )) return super.loadIcon( arg1); return (android.graphics.drawable.Drawable) jInterface.Jnido( this, jchildidx + "loadIcon_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void writeToParcel(android.os.Parcel arg1,int arg2) { if (!testjnOverride( "writeToParcel" )) { super.writeToParcel( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "writeToParcel_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void readFromParcel(android.os.Parcel arg1) { if (!testjnOverride( "readFromParcel" )) { super.readFromParcel( arg1); return; } jInterface.Jnido( this, jchildidx + "readFromParcel_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
