.TH JCONSOLE 1 "Sept 2002"
.SH NAME
jconsole \- command line J interpreter
.SH SYNOPSIS
.B jconsole
.RI [ "options and arguments..." ]
.SH DESCRIPTION
.B jconsole
runs the J interpreter and Control-d exits.

The J installation has complete documentation in HTML format. Start at:
   system/extras/help/index.htm 

For information about Jsoftware and J systems see:
   www.jsoftware.com

.SH OPTIONS and Environment
See the HTML documentation for more information.
