package org.dykman.jn.android.app;
public class Activity extends android.app.Activity{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList<Object> jnOverrideList = null;
protected java.lang.String japparg = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public Activity(){ super(); jnOverrideList = new java.util.ArrayList<Object>(); jnOverrideList.add ("onCreate"); }
@Override protected void finalize() throws java.lang.Throwable{ if (!testjnOverride( "finalize" )) { super.finalize(); return; } jInterface.Jnido( this, jchildidx + "finalize_" + jlocale + "_", null ); }
@Override public android.content.Intent getIntent(){ if (!testjnOverride( "getIntent" )) return super.getIntent(); return (android.content.Intent) jInterface.Jnido( this, jchildidx + "getIntent_" + jlocale + "_", null ); }
@Override public void setIntent(android.content.Intent arg1) { if (!testjnOverride( "setIntent" )) { super.setIntent( arg1); return; } jInterface.Jnido( this, jchildidx + "setIntent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.view.WindowManager getWindowManager(){ if (!testjnOverride( "getWindowManager" )) return super.getWindowManager(); return (android.view.WindowManager) jInterface.Jnido( this, jchildidx + "getWindowManager_" + jlocale + "_", null ); }
@Override public android.view.Window getWindow(){ if (!testjnOverride( "getWindow" )) return super.getWindow(); return (android.view.Window) jInterface.Jnido( this, jchildidx + "getWindow_" + jlocale + "_", null ); }
@Override public android.view.View getCurrentFocus(){ if (!testjnOverride( "getCurrentFocus" )) return super.getCurrentFocus(); return (android.view.View) jInterface.Jnido( this, jchildidx + "getCurrentFocus_" + jlocale + "_", null ); }
@Override public int getWallpaperDesiredMinimumWidth(){ if (!testjnOverride( "getWallpaperDesiredMinimumWidth" )) return super.getWallpaperDesiredMinimumWidth(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getWallpaperDesiredMinimumWidth_" + jlocale + "_", null ); }
@Override public int getWallpaperDesiredMinimumHeight(){ if (!testjnOverride( "getWallpaperDesiredMinimumHeight" )) return super.getWallpaperDesiredMinimumHeight(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getWallpaperDesiredMinimumHeight_" + jlocale + "_", null ); }
@Override protected void onCreate(android.os.Bundle arg1) { if (!testjnOverride( "onCreate" )) { super.onCreate( arg1); return; } else super.onCreate( arg1); japparg = getIntent().getStringExtra("japparg"); jparseargs( getIntent().getStringExtra("locale"), null, getIntent().getStringExtra("override") ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; jInterface.Jnido( this, jchildidx + "onCreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onRestoreInstanceState(android.os.Bundle arg1) { if (!testjnOverride( "onRestoreInstanceState" )) { super.onRestoreInstanceState( arg1); return; } jInterface.Jnido( this, jchildidx + "onRestoreInstanceState_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onPostCreate(android.os.Bundle arg1) { if (!testjnOverride( "onPostCreate" )) { super.onPostCreate( arg1); return; } else super.onPostCreate( arg1); jInterface.Jnido( this, jchildidx + "onPostCreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onStart(){ if (!testjnOverride( "onStart" )) { super.onStart(); return; } else super.onStart(); jInterface.Jnido( this, jchildidx + "onStart_" + jlocale + "_", null ); }
@Override protected void onRestart(){ if (!testjnOverride( "onRestart" )) { super.onRestart(); return; } else super.onRestart(); jInterface.Jnido( this, jchildidx + "onRestart_" + jlocale + "_", null ); }
@Override protected void onResume(){ if (!testjnOverride( "onResume" )) { super.onResume(); return; } else super.onResume(); jInterface.Jnido( this, jchildidx + "onResume_" + jlocale + "_", null ); }
@Override protected void onPostResume(){ if (!testjnOverride( "onPostResume" )) { super.onPostResume(); return; } else super.onPostResume(); jInterface.Jnido( this, jchildidx + "onPostResume_" + jlocale + "_", null ); }
@Override protected void onNewIntent(android.content.Intent arg1) { if (!testjnOverride( "onNewIntent" )) { super.onNewIntent( arg1); return; } jInterface.Jnido( this, jchildidx + "onNewIntent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onSaveInstanceState(android.os.Bundle arg1) { if (!testjnOverride( "onSaveInstanceState" )) { super.onSaveInstanceState( arg1); return; } jInterface.Jnido( this, jchildidx + "onSaveInstanceState_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onPause(){ if (!testjnOverride( "onPause" )) { super.onPause(); return; } else super.onPause(); jInterface.Jnido( this, jchildidx + "onPause_" + jlocale + "_", null ); }
@Override protected void onUserLeaveHint(){ if (!testjnOverride( "onUserLeaveHint" )) { super.onUserLeaveHint(); return; } jInterface.Jnido( this, jchildidx + "onUserLeaveHint_" + jlocale + "_", null ); }
@Override public boolean onCreateThumbnail(android.graphics.Bitmap arg1,android.graphics.Canvas arg2) { if (!testjnOverride( "onCreateThumbnail" )) return super.onCreateThumbnail( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onCreateThumbnail_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public java.lang.CharSequence onCreateDescription(){ if (!testjnOverride( "onCreateDescription" )) return super.onCreateDescription(); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "onCreateDescription_" + jlocale + "_", null ); }
@Override protected void onStop(){ if (!testjnOverride( "onStop" )) { super.onStop(); return; } else super.onStop(); jInterface.Jnido( this, jchildidx + "onStop_" + jlocale + "_", null ); }
@Override protected void onDestroy(){ if (!testjnOverride( "onDestroy" )) { super.onDestroy(); return; } else super.onDestroy(); jInterface.Jnido( this, jchildidx + "onDestroy_" + jlocale + "_", null ); }
@Override public void onConfigurationChanged(android.content.res.Configuration arg1) { if (!testjnOverride( "onConfigurationChanged" )) { super.onConfigurationChanged( arg1); return; } jInterface.Jnido( this, jchildidx + "onConfigurationChanged_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getChangingConfigurations(){ if (!testjnOverride( "getChangingConfigurations" )) return super.getChangingConfigurations(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getChangingConfigurations_" + jlocale + "_", null ); }
@Override public java.lang.Object getLastNonConfigurationInstance(){ if (!testjnOverride( "getLastNonConfigurationInstance" )) return super.getLastNonConfigurationInstance(); return (java.lang.Object) jInterface.Jnido( this, jchildidx + "getLastNonConfigurationInstance_" + jlocale + "_", null ); }
@Override public java.lang.Object onRetainNonConfigurationInstance(){ if (!testjnOverride( "onRetainNonConfigurationInstance" )) return super.onRetainNonConfigurationInstance(); return (java.lang.Object) jInterface.Jnido( this, jchildidx + "onRetainNonConfigurationInstance_" + jlocale + "_", null ); }
@Override public void onLowMemory(){ if (!testjnOverride( "onLowMemory" )) { super.onLowMemory(); return; } jInterface.Jnido( this, jchildidx + "onLowMemory_" + jlocale + "_", null ); }
@Override public void startManagingCursor(android.database.Cursor arg1) { if (!testjnOverride( "startManagingCursor" )) { super.startManagingCursor( arg1); return; } jInterface.Jnido( this, jchildidx + "startManagingCursor_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void stopManagingCursor(android.database.Cursor arg1) { if (!testjnOverride( "stopManagingCursor" )) { super.stopManagingCursor( arg1); return; } jInterface.Jnido( this, jchildidx + "stopManagingCursor_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.view.View findViewById(int arg1) { if (!testjnOverride( "findViewById" )) return super.findViewById( arg1); return (android.view.View) jInterface.Jnido( this, jchildidx + "findViewById_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setContentView(int arg1) { if (!testjnOverride( "setContentView" )) { super.setContentView( arg1); return; } jInterface.Jnido( this, jchildidx + "setContentView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setContentView(android.view.View arg1) { if (!testjnOverride( "setContentView" )) { super.setContentView( arg1); return; } jInterface.Jnido( this, jchildidx + "setContentView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setContentView(android.view.View arg1,android.view.ViewGroup.LayoutParams arg2) { if (!testjnOverride( "setContentView" )) { super.setContentView( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setContentView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void addContentView(android.view.View arg1,android.view.ViewGroup.LayoutParams arg2) { if (!testjnOverride( "addContentView" )) { super.addContentView( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "addContentView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onKeyDown(int arg1,android.view.KeyEvent arg2) { if (!testjnOverride( "onKeyDown" )) return super.onKeyDown( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyDown_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onKeyLongPress(int arg1,android.view.KeyEvent arg2) { if (!testjnOverride( "onKeyLongPress" )) return super.onKeyLongPress( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyLongPress_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onKeyUp(int arg1,android.view.KeyEvent arg2) { if (!testjnOverride( "onKeyUp" )) return super.onKeyUp( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyUp_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onKeyMultiple(int arg1,int arg2,android.view.KeyEvent arg3) { if (!testjnOverride( "onKeyMultiple" )) return super.onKeyMultiple( arg1, arg2, arg3); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyMultiple_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void onBackPressed(){ if (!testjnOverride( "onBackPressed" )) { super.onBackPressed(); return; } jInterface.Jnido( this, jchildidx + "onBackPressed_" + jlocale + "_", null ); }
@Override public boolean onTouchEvent(android.view.MotionEvent arg1) { if (!testjnOverride( "onTouchEvent" )) return super.onTouchEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onTouchEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onTrackballEvent(android.view.MotionEvent arg1) { if (!testjnOverride( "onTrackballEvent" )) return super.onTrackballEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onTrackballEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void onUserInteraction(){ if (!testjnOverride( "onUserInteraction" )) { super.onUserInteraction(); return; } jInterface.Jnido( this, jchildidx + "onUserInteraction_" + jlocale + "_", null ); }
@Override public void onWindowAttributesChanged(android.view.WindowManager.LayoutParams arg1) { if (!testjnOverride( "onWindowAttributesChanged" )) { super.onWindowAttributesChanged( arg1); return; } jInterface.Jnido( this, jchildidx + "onWindowAttributesChanged_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void onContentChanged(){ if (!testjnOverride( "onContentChanged" )) { super.onContentChanged(); return; } jInterface.Jnido( this, jchildidx + "onContentChanged_" + jlocale + "_", null ); }
@Override public void onWindowFocusChanged(boolean arg1) { if (!testjnOverride( "onWindowFocusChanged" )) { super.onWindowFocusChanged( arg1); return; } jInterface.Jnido( this, jchildidx + "onWindowFocusChanged_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void onAttachedToWindow(){ if (!testjnOverride( "onAttachedToWindow" )) { super.onAttachedToWindow(); return; } jInterface.Jnido( this, jchildidx + "onAttachedToWindow_" + jlocale + "_", null ); }
@Override public void onDetachedFromWindow(){ if (!testjnOverride( "onDetachedFromWindow" )) { super.onDetachedFromWindow(); return; } jInterface.Jnido( this, jchildidx + "onDetachedFromWindow_" + jlocale + "_", null ); }
@Override public boolean hasWindowFocus(){ if (!testjnOverride( "hasWindowFocus" )) return super.hasWindowFocus(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "hasWindowFocus_" + jlocale + "_", null ); }
@Override public boolean dispatchKeyEvent(android.view.KeyEvent arg1) { if (!testjnOverride( "dispatchKeyEvent" )) return super.dispatchKeyEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "dispatchKeyEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean dispatchTouchEvent(android.view.MotionEvent arg1) { if (!testjnOverride( "dispatchTouchEvent" )) return super.dispatchTouchEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "dispatchTouchEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean dispatchTrackballEvent(android.view.MotionEvent arg1) { if (!testjnOverride( "dispatchTrackballEvent" )) return super.dispatchTrackballEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "dispatchTrackballEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean dispatchPopulateAccessibilityEvent(android.view.accessibility.AccessibilityEvent arg1) { if (!testjnOverride( "dispatchPopulateAccessibilityEvent" )) return super.dispatchPopulateAccessibilityEvent( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "dispatchPopulateAccessibilityEvent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.view.View onCreatePanelView(int arg1) { if (!testjnOverride( "onCreatePanelView" )) return super.onCreatePanelView( arg1); return (android.view.View) jInterface.Jnido( this, jchildidx + "onCreatePanelView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onCreatePanelMenu(int arg1,android.view.Menu arg2) { if (!testjnOverride( "onCreatePanelMenu" )) return super.onCreatePanelMenu( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onCreatePanelMenu_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onPreparePanel(int arg1,android.view.View arg2,android.view.Menu arg3) { if (!testjnOverride( "onPreparePanel" )) return super.onPreparePanel( arg1, arg2, arg3); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onPreparePanel_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public boolean onMenuOpened(int arg1,android.view.Menu arg2) { if (!testjnOverride( "onMenuOpened" )) return super.onMenuOpened( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onMenuOpened_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onMenuItemSelected(int arg1,android.view.MenuItem arg2) { if (!testjnOverride( "onMenuItemSelected" )) return super.onMenuItemSelected( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onMenuItemSelected_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void onPanelClosed(int arg1,android.view.Menu arg2) { if (!testjnOverride( "onPanelClosed" )) { super.onPanelClosed( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onPanelClosed_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onCreateOptionsMenu(android.view.Menu arg1) { if (!testjnOverride( "onCreateOptionsMenu" )) return super.onCreateOptionsMenu( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onCreateOptionsMenu_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onPrepareOptionsMenu(android.view.Menu arg1) { if (!testjnOverride( "onPrepareOptionsMenu" )) return super.onPrepareOptionsMenu( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onPrepareOptionsMenu_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onOptionsItemSelected(android.view.MenuItem arg1) { if (!testjnOverride( "onOptionsItemSelected" )) return super.onOptionsItemSelected( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onOptionsItemSelected_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void onOptionsMenuClosed(android.view.Menu arg1) { if (!testjnOverride( "onOptionsMenuClosed" )) { super.onOptionsMenuClosed( arg1); return; } jInterface.Jnido( this, jchildidx + "onOptionsMenuClosed_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void openOptionsMenu(){ if (!testjnOverride( "openOptionsMenu" )) { super.openOptionsMenu(); return; } jInterface.Jnido( this, jchildidx + "openOptionsMenu_" + jlocale + "_", null ); }
@Override public void closeOptionsMenu(){ if (!testjnOverride( "closeOptionsMenu" )) { super.closeOptionsMenu(); return; } jInterface.Jnido( this, jchildidx + "closeOptionsMenu_" + jlocale + "_", null ); }
@Override public void onCreateContextMenu(android.view.ContextMenu arg1,android.view.View arg2,android.view.ContextMenu.ContextMenuInfo arg3) { if (!testjnOverride( "onCreateContextMenu" )) { super.onCreateContextMenu( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "onCreateContextMenu_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void registerForContextMenu(android.view.View arg1) { if (!testjnOverride( "registerForContextMenu" )) { super.registerForContextMenu( arg1); return; } jInterface.Jnido( this, jchildidx + "registerForContextMenu_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void unregisterForContextMenu(android.view.View arg1) { if (!testjnOverride( "unregisterForContextMenu" )) { super.unregisterForContextMenu( arg1); return; } jInterface.Jnido( this, jchildidx + "unregisterForContextMenu_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void openContextMenu(android.view.View arg1) { if (!testjnOverride( "openContextMenu" )) { super.openContextMenu( arg1); return; } jInterface.Jnido( this, jchildidx + "openContextMenu_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void closeContextMenu(){ if (!testjnOverride( "closeContextMenu" )) { super.closeContextMenu(); return; } jInterface.Jnido( this, jchildidx + "closeContextMenu_" + jlocale + "_", null ); }
@Override public boolean onContextItemSelected(android.view.MenuItem arg1) { if (!testjnOverride( "onContextItemSelected" )) return super.onContextItemSelected( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onContextItemSelected_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void onContextMenuClosed(android.view.Menu arg1) { if (!testjnOverride( "onContextMenuClosed" )) { super.onContextMenuClosed( arg1); return; } jInterface.Jnido( this, jchildidx + "onContextMenuClosed_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected android.app.Dialog onCreateDialog(int arg1) { if (!testjnOverride( "onCreateDialog" )) return super.onCreateDialog( arg1); return (android.app.Dialog) jInterface.Jnido( this, jchildidx + "onCreateDialog_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onPrepareDialog(int arg1,android.app.Dialog arg2) { if (!testjnOverride( "onPrepareDialog" )) { super.onPrepareDialog( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onPrepareDialog_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onSearchRequested(){ if (!testjnOverride( "onSearchRequested" )) return super.onSearchRequested(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onSearchRequested_" + jlocale + "_", null ); }
@Override public void startSearch(java.lang.String arg1,boolean arg2,android.os.Bundle arg3,boolean arg4) { if (!testjnOverride( "startSearch" )) { super.startSearch( arg1, arg2, arg3, arg4); return; } jInterface.Jnido( this, jchildidx + "startSearch_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4 } ); }
@Override public void triggerSearch(java.lang.String arg1,android.os.Bundle arg2) { if (!testjnOverride( "triggerSearch" )) { super.triggerSearch( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "triggerSearch_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void takeKeyEvents(boolean arg1) { if (!testjnOverride( "takeKeyEvents" )) { super.takeKeyEvents( arg1); return; } jInterface.Jnido( this, jchildidx + "takeKeyEvents_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.view.LayoutInflater getLayoutInflater(){ if (!testjnOverride( "getLayoutInflater" )) return super.getLayoutInflater(); return (android.view.LayoutInflater) jInterface.Jnido( this, jchildidx + "getLayoutInflater_" + jlocale + "_", null ); }
@Override public android.view.MenuInflater getMenuInflater(){ if (!testjnOverride( "getMenuInflater" )) return super.getMenuInflater(); return (android.view.MenuInflater) jInterface.Jnido( this, jchildidx + "getMenuInflater_" + jlocale + "_", null ); }
@Override protected void onApplyThemeResource(android.content.res.Resources.Theme arg1,int arg2,boolean arg3) { if (!testjnOverride( "onApplyThemeResource" )) { super.onApplyThemeResource( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "onApplyThemeResource_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void startActivityForResult(android.content.Intent arg1,int arg2) { if (!testjnOverride( "startActivityForResult" )) { super.startActivityForResult( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "startActivityForResult_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void startIntentSenderForResult(android.content.IntentSender arg1,int arg2,android.content.Intent arg3,int arg4,int arg5,int arg6) throws android.content.IntentSender.SendIntentException { if (!testjnOverride( "startIntentSenderForResult" )) { super.startIntentSenderForResult( arg1, arg2, arg3, arg4, arg5, arg6); return; } jInterface.Jnido( this, jchildidx + "startIntentSenderForResult_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5, arg6 } ); }
@Override public void startActivity(android.content.Intent arg1) { if (!testjnOverride( "startActivity" )) { super.startActivity( arg1); return; } jInterface.Jnido( this, jchildidx + "startActivity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void startIntentSender(android.content.IntentSender arg1,android.content.Intent arg2,int arg3,int arg4,int arg5) throws android.content.IntentSender.SendIntentException { if (!testjnOverride( "startIntentSender" )) { super.startIntentSender( arg1, arg2, arg3, arg4, arg5); return; } jInterface.Jnido( this, jchildidx + "startIntentSender_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5 } ); }
@Override public boolean startActivityIfNeeded(android.content.Intent arg1,int arg2) { if (!testjnOverride( "startActivityIfNeeded" )) return super.startActivityIfNeeded( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "startActivityIfNeeded_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean startNextMatchingActivity(android.content.Intent arg1) { if (!testjnOverride( "startNextMatchingActivity" )) return super.startNextMatchingActivity( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "startNextMatchingActivity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void startActivityFromChild(android.app.Activity arg1,android.content.Intent arg2,int arg3) { if (!testjnOverride( "startActivityFromChild" )) { super.startActivityFromChild( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "startActivityFromChild_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void startIntentSenderFromChild(android.app.Activity arg1,android.content.IntentSender arg2,int arg3,android.content.Intent arg4,int arg5,int arg6,int arg7) throws android.content.IntentSender.SendIntentException { if (!testjnOverride( "startIntentSenderFromChild" )) { super.startIntentSenderFromChild( arg1, arg2, arg3, arg4, arg5, arg6, arg7); return; } jInterface.Jnido( this, jchildidx + "startIntentSenderFromChild_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5, arg6, arg7 } ); }
@Override public void overridePendingTransition(int arg1,int arg2) { if (!testjnOverride( "overridePendingTransition" )) { super.overridePendingTransition( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "overridePendingTransition_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public java.lang.String getCallingPackage(){ if (!testjnOverride( "getCallingPackage" )) return super.getCallingPackage(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getCallingPackage_" + jlocale + "_", null ); }
@Override public android.content.ComponentName getCallingActivity(){ if (!testjnOverride( "getCallingActivity" )) return super.getCallingActivity(); return (android.content.ComponentName) jInterface.Jnido( this, jchildidx + "getCallingActivity_" + jlocale + "_", null ); }
@Override public void setVisible(boolean arg1) { if (!testjnOverride( "setVisible" )) { super.setVisible( arg1); return; } jInterface.Jnido( this, jchildidx + "setVisible_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean isFinishing(){ if (!testjnOverride( "isFinishing" )) return super.isFinishing(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isFinishing_" + jlocale + "_", null ); }
@Override public void finish(){ if (!testjnOverride( "finish" )) { super.finish(); return; } jInterface.Jnido( this, jchildidx + "finish_" + jlocale + "_", null ); }
@Override public void finishFromChild(android.app.Activity arg1) { if (!testjnOverride( "finishFromChild" )) { super.finishFromChild( arg1); return; } jInterface.Jnido( this, jchildidx + "finishFromChild_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void finishActivity(int arg1) { if (!testjnOverride( "finishActivity" )) { super.finishActivity( arg1); return; } jInterface.Jnido( this, jchildidx + "finishActivity_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void finishActivityFromChild(android.app.Activity arg1,int arg2) { if (!testjnOverride( "finishActivityFromChild" )) { super.finishActivityFromChild( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "finishActivityFromChild_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onActivityResult(int arg1,int arg2,android.content.Intent arg3) { if (!testjnOverride( "onActivityResult" )) { super.onActivityResult( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "onActivityResult_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public android.app.PendingIntent createPendingResult(int arg1,android.content.Intent arg2,int arg3) { if (!testjnOverride( "createPendingResult" )) return super.createPendingResult( arg1, arg2, arg3); return (android.app.PendingIntent) jInterface.Jnido( this, jchildidx + "createPendingResult_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void setRequestedOrientation(int arg1) { if (!testjnOverride( "setRequestedOrientation" )) { super.setRequestedOrientation( arg1); return; } jInterface.Jnido( this, jchildidx + "setRequestedOrientation_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getRequestedOrientation(){ if (!testjnOverride( "getRequestedOrientation" )) return super.getRequestedOrientation(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getRequestedOrientation_" + jlocale + "_", null ); }
@Override public int getTaskId(){ if (!testjnOverride( "getTaskId" )) return super.getTaskId(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getTaskId_" + jlocale + "_", null ); }
@Override public boolean isTaskRoot(){ if (!testjnOverride( "isTaskRoot" )) return super.isTaskRoot(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isTaskRoot_" + jlocale + "_", null ); }
@Override public boolean moveTaskToBack(boolean arg1) { if (!testjnOverride( "moveTaskToBack" )) return super.moveTaskToBack( arg1); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "moveTaskToBack_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.String getLocalClassName(){ if (!testjnOverride( "getLocalClassName" )) return super.getLocalClassName(); return (java.lang.String) jInterface.Jnido( this, jchildidx + "getLocalClassName_" + jlocale + "_", null ); }
@Override public android.content.ComponentName getComponentName(){ if (!testjnOverride( "getComponentName" )) return super.getComponentName(); return (android.content.ComponentName) jInterface.Jnido( this, jchildidx + "getComponentName_" + jlocale + "_", null ); }
@Override public android.content.SharedPreferences getPreferences(int arg1) { if (!testjnOverride( "getPreferences" )) return super.getPreferences( arg1); return (android.content.SharedPreferences) jInterface.Jnido( this, jchildidx + "getPreferences_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.Object getSystemService(java.lang.String arg1) { if (!testjnOverride( "getSystemService" )) return super.getSystemService( arg1); return (java.lang.Object) jInterface.Jnido( this, jchildidx + "getSystemService_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setTitle(java.lang.CharSequence arg1) { if (!testjnOverride( "setTitle" )) { super.setTitle( arg1); return; } jInterface.Jnido( this, jchildidx + "setTitle_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setTitle(int arg1) { if (!testjnOverride( "setTitle" )) { super.setTitle( arg1); return; } jInterface.Jnido( this, jchildidx + "setTitle_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setTitleColor(int arg1) { if (!testjnOverride( "setTitleColor" )) { super.setTitleColor( arg1); return; } jInterface.Jnido( this, jchildidx + "setTitleColor_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onTitleChanged(java.lang.CharSequence arg1,int arg2) { if (!testjnOverride( "onTitleChanged" )) { super.onTitleChanged( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onTitleChanged_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onChildTitleChanged(android.app.Activity arg1,java.lang.CharSequence arg2) { if (!testjnOverride( "onChildTitleChanged" )) { super.onChildTitleChanged( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onChildTitleChanged_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public android.view.View onCreateView(java.lang.String arg1,android.content.Context arg2,android.util.AttributeSet arg3) { if (!testjnOverride( "onCreateView" )) return super.onCreateView( arg1, arg2, arg3); return (android.view.View) jInterface.Jnido( this, jchildidx + "onCreateView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
}
