package org.dykman.jn.android.app;
public class AlertDialog extends android.app.AlertDialog{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
protected AlertDialog(android.content.Context arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
protected AlertDialog(android.content.Context arg1,int arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
protected AlertDialog(android.content.Context arg1,boolean arg2,android.content.DialogInterface.OnCancelListener arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public android.widget.Button getButton(int arg1) { if (!testjnOverride( "getButton" )) return super.getButton( arg1); return (android.widget.Button) jInterface.Jnido( this, jchildidx + "getButton_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public android.widget.ListView getListView(){ if (!testjnOverride( "getListView" )) return super.getListView(); return (android.widget.ListView) jInterface.Jnido( this, jchildidx + "getListView_" + jlocale + "_", null ); }
@Override public void setTitle(java.lang.CharSequence arg1) { if (!testjnOverride( "setTitle" )) { super.setTitle( arg1); return; } jInterface.Jnido( this, jchildidx + "setTitle_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setCustomTitle(android.view.View arg1) { if (!testjnOverride( "setCustomTitle" )) { super.setCustomTitle( arg1); return; } jInterface.Jnido( this, jchildidx + "setCustomTitle_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setMessage(java.lang.CharSequence arg1) { if (!testjnOverride( "setMessage" )) { super.setMessage( arg1); return; } jInterface.Jnido( this, jchildidx + "setMessage_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setView(android.view.View arg1) { if (!testjnOverride( "setView" )) { super.setView( arg1); return; } jInterface.Jnido( this, jchildidx + "setView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setView(android.view.View arg1,int arg2,int arg3,int arg4,int arg5) { if (!testjnOverride( "setView" )) { super.setView( arg1, arg2, arg3, arg4, arg5); return; } jInterface.Jnido( this, jchildidx + "setView_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3, arg4, arg5 } ); }
@Override public void setButton(int arg1,java.lang.CharSequence arg2,android.os.Message arg3) { if (!testjnOverride( "setButton" )) { super.setButton( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "setButton_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void setButton(int arg1,java.lang.CharSequence arg2,android.content.DialogInterface.OnClickListener arg3) { if (!testjnOverride( "setButton" )) { super.setButton( arg1, arg2, arg3); return; } jInterface.Jnido( this, jchildidx + "setButton_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
@Override public void setButton(java.lang.CharSequence arg1,android.os.Message arg2) { if (!testjnOverride( "setButton" )) { super.setButton( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setButton(java.lang.CharSequence arg1,android.content.DialogInterface.OnClickListener arg2) { if (!testjnOverride( "setButton" )) { super.setButton( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setButton2(java.lang.CharSequence arg1,android.os.Message arg2) { if (!testjnOverride( "setButton2" )) { super.setButton2( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton2_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setButton2(java.lang.CharSequence arg1,android.content.DialogInterface.OnClickListener arg2) { if (!testjnOverride( "setButton2" )) { super.setButton2( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton2_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setButton3(java.lang.CharSequence arg1,android.os.Message arg2) { if (!testjnOverride( "setButton3" )) { super.setButton3( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton3_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setButton3(java.lang.CharSequence arg1,android.content.DialogInterface.OnClickListener arg2) { if (!testjnOverride( "setButton3" )) { super.setButton3( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "setButton3_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public void setIcon(int arg1) { if (!testjnOverride( "setIcon" )) { super.setIcon( arg1); return; } jInterface.Jnido( this, jchildidx + "setIcon_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setIcon(android.graphics.drawable.Drawable arg1) { if (!testjnOverride( "setIcon" )) { super.setIcon( arg1); return; } jInterface.Jnido( this, jchildidx + "setIcon_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setInverseBackgroundForced(boolean arg1) { if (!testjnOverride( "setInverseBackgroundForced" )) { super.setInverseBackgroundForced( arg1); return; } jInterface.Jnido( this, jchildidx + "setInverseBackgroundForced_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onCreate(android.os.Bundle arg1) { if (!testjnOverride( "onCreate" )) { super.onCreate( arg1); return; } jInterface.Jnido( this, jchildidx + "onCreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onKeyDown(int arg1,android.view.KeyEvent arg2) { if (!testjnOverride( "onKeyDown" )) return super.onKeyDown( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyDown_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override public boolean onKeyUp(int arg1,android.view.KeyEvent arg2) { if (!testjnOverride( "onKeyUp" )) return super.onKeyUp( arg1, arg2); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onKeyUp_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
}
