package org.dykman.jn.android.preference;
public class CheckBoxPreference extends android.preference.CheckBoxPreference{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public CheckBoxPreference(android.content.Context arg1,android.util.AttributeSet arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
public CheckBoxPreference(android.content.Context arg1,android.util.AttributeSet arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public CheckBoxPreference(android.content.Context arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onBindView(android.view.View arg1) { if (!testjnOverride( "onBindView" )) { super.onBindView( arg1); return; } jInterface.Jnido( this, jchildidx + "onBindView_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onClick(){ if (!testjnOverride( "onClick" )) { super.onClick(); return; } jInterface.Jnido( this, jchildidx + "onClick_" + jlocale + "_", null ); }
@Override public void setChecked(boolean arg1) { if (!testjnOverride( "setChecked" )) { super.setChecked( arg1); return; } jInterface.Jnido( this, jchildidx + "setChecked_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean isChecked(){ if (!testjnOverride( "isChecked" )) return super.isChecked(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "isChecked_" + jlocale + "_", null ); }
@Override public boolean shouldDisableDependents(){ if (!testjnOverride( "shouldDisableDependents" )) return super.shouldDisableDependents(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "shouldDisableDependents_" + jlocale + "_", null ); }
@Override public void setSummaryOn(java.lang.CharSequence arg1) { if (!testjnOverride( "setSummaryOn" )) { super.setSummaryOn( arg1); return; } jInterface.Jnido( this, jchildidx + "setSummaryOn_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setSummaryOn(int arg1) { if (!testjnOverride( "setSummaryOn" )) { super.setSummaryOn( arg1); return; } jInterface.Jnido( this, jchildidx + "setSummaryOn_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.CharSequence getSummaryOn(){ if (!testjnOverride( "getSummaryOn" )) return super.getSummaryOn(); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "getSummaryOn_" + jlocale + "_", null ); }
@Override public void setSummaryOff(java.lang.CharSequence arg1) { if (!testjnOverride( "setSummaryOff" )) { super.setSummaryOff( arg1); return; } jInterface.Jnido( this, jchildidx + "setSummaryOff_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public void setSummaryOff(int arg1) { if (!testjnOverride( "setSummaryOff" )) { super.setSummaryOff( arg1); return; } jInterface.Jnido( this, jchildidx + "setSummaryOff_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public java.lang.CharSequence getSummaryOff(){ if (!testjnOverride( "getSummaryOff" )) return super.getSummaryOff(); return (java.lang.CharSequence) jInterface.Jnido( this, jchildidx + "getSummaryOff_" + jlocale + "_", null ); }
@Override public boolean getDisableDependentsState(){ if (!testjnOverride( "getDisableDependentsState" )) return super.getDisableDependentsState(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getDisableDependentsState_" + jlocale + "_", null ); }
@Override public void setDisableDependentsState(boolean arg1) { if (!testjnOverride( "setDisableDependentsState" )) { super.setDisableDependentsState( arg1); return; } jInterface.Jnido( this, jchildidx + "setDisableDependentsState_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected java.lang.Object onGetDefaultValue(android.content.res.TypedArray arg1,int arg2) { if (!testjnOverride( "onGetDefaultValue" )) return super.onGetDefaultValue( arg1, arg2); return (java.lang.Object) jInterface.Jnido( this, jchildidx + "onGetDefaultValue_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onSetInitialValue(boolean arg1,java.lang.Object arg2) { if (!testjnOverride( "onSetInitialValue" )) { super.onSetInitialValue( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onSetInitialValue_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected android.os.Parcelable onSaveInstanceState(){ if (!testjnOverride( "onSaveInstanceState" )) return super.onSaveInstanceState(); return (android.os.Parcelable) jInterface.Jnido( this, jchildidx + "onSaveInstanceState_" + jlocale + "_", null ); }
@Override protected void onRestoreInstanceState(android.os.Parcelable arg1) { if (!testjnOverride( "onRestoreInstanceState" )) { super.onRestoreInstanceState( arg1); return; } jInterface.Jnido( this, jchildidx + "onRestoreInstanceState_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
}
