package org.dykman.jn.android.preference;
public class RingtonePreference extends android.preference.RingtonePreference{
protected org.dykman.j.JInterface jInterface = null;
protected java.lang.String jlocale = null;
protected java.lang.String jchildid = null;
protected java.lang.String jchildidx = null;
protected java.util.ArrayList jnOverrideList = null;
protected void jparseargs (java.lang.String jlocale, java.lang.String jchildid, java.lang.String joverride ) { this.jlocale = jlocale; this.jchildid = jchildid; if (jchildid != null && jchildid.length() > 0) jchildidx = jchildid + "_"; else jchildidx = ""; if (joverride != null && joverride.length() > 0) { java.lang.String[] ss = joverride.split(" "); for (int i = 0; i < ss.length; i++) setjnOverride(ss[i]); } }
public void clearjnOverride () { jnOverrideList.clear (); }
public void setjnOverride (java.lang.String arg1 ) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); }
public void setjnOverride (java.lang.String arg1, boolean arg2 ) { if (arg2) { if (!testjnOverride (arg1)) jnOverrideList.add (arg1); } else jnOverrideList.remove (arg1); }
public boolean testjnOverride (java.lang.String arg1 ) { return jnOverrideList.contains (arg1); }
public RingtonePreference(android.content.Context arg1,android.util.AttributeSet arg2,int arg3, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2, arg3); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
public RingtonePreference(android.content.Context arg1,android.util.AttributeSet arg2, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1, arg2); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
public RingtonePreference(android.content.Context arg1, java.lang.String jlocale,String jchildid,String joverride ) { super( arg1); jnOverrideList = new java.util.ArrayList(); jparseargs( jlocale, jchildid, joverride ); jInterface = org.dykman.j.android.JConsoleApp.theApp.jInterface; if (testjnOverride( "jcreate" )) jInterface.Jnido( this, jchildidx + "jcreate_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public int getRingtoneType(){ if (!testjnOverride( "getRingtoneType" )) return super.getRingtoneType(); return (java.lang.Integer) jInterface.Jnido( this, jchildidx + "getRingtoneType_" + jlocale + "_", null ); }
@Override public void setRingtoneType(int arg1) { if (!testjnOverride( "setRingtoneType" )) { super.setRingtoneType( arg1); return; } jInterface.Jnido( this, jchildidx + "setRingtoneType_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean getShowDefault(){ if (!testjnOverride( "getShowDefault" )) return super.getShowDefault(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getShowDefault_" + jlocale + "_", null ); }
@Override public void setShowDefault(boolean arg1) { if (!testjnOverride( "setShowDefault" )) { super.setShowDefault( arg1); return; } jInterface.Jnido( this, jchildidx + "setShowDefault_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean getShowSilent(){ if (!testjnOverride( "getShowSilent" )) return super.getShowSilent(); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "getShowSilent_" + jlocale + "_", null ); }
@Override public void setShowSilent(boolean arg1) { if (!testjnOverride( "setShowSilent" )) { super.setShowSilent( arg1); return; } jInterface.Jnido( this, jchildidx + "setShowSilent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onClick(){ if (!testjnOverride( "onClick" )) { super.onClick(); return; } jInterface.Jnido( this, jchildidx + "onClick_" + jlocale + "_", null ); }
@Override protected void onPrepareRingtonePickerIntent(android.content.Intent arg1) { if (!testjnOverride( "onPrepareRingtonePickerIntent" )) { super.onPrepareRingtonePickerIntent( arg1); return; } jInterface.Jnido( this, jchildidx + "onPrepareRingtonePickerIntent_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected void onSaveRingtone(android.net.Uri arg1) { if (!testjnOverride( "onSaveRingtone" )) { super.onSaveRingtone( arg1); return; } jInterface.Jnido( this, jchildidx + "onSaveRingtone_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override protected android.net.Uri onRestoreRingtone(){ if (!testjnOverride( "onRestoreRingtone" )) return super.onRestoreRingtone(); return (android.net.Uri) jInterface.Jnido( this, jchildidx + "onRestoreRingtone_" + jlocale + "_", null ); }
@Override protected java.lang.Object onGetDefaultValue(android.content.res.TypedArray arg1,int arg2) { if (!testjnOverride( "onGetDefaultValue" )) return super.onGetDefaultValue( arg1, arg2); return (java.lang.Object) jInterface.Jnido( this, jchildidx + "onGetDefaultValue_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onSetInitialValue(boolean arg1,java.lang.Object arg2) { if (!testjnOverride( "onSetInitialValue" )) { super.onSetInitialValue( arg1, arg2); return; } jInterface.Jnido( this, jchildidx + "onSetInitialValue_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2 } ); }
@Override protected void onAttachedToHierarchy(android.preference.PreferenceManager arg1) { if (!testjnOverride( "onAttachedToHierarchy" )) { super.onAttachedToHierarchy( arg1); return; } jInterface.Jnido( this, jchildidx + "onAttachedToHierarchy_" + jlocale + "_", new java.lang.Object[]{ arg1 } ); }
@Override public boolean onActivityResult(int arg1,int arg2,android.content.Intent arg3) { if (!testjnOverride( "onActivityResult" )) return super.onActivityResult( arg1, arg2, arg3); return (java.lang.Boolean) jInterface.Jnido( this, jchildidx + "onActivityResult_" + jlocale + "_", new java.lang.Object[]{ arg1, arg2, arg3 } ); }
}
